### ISSUE TITLE
could you offer me the original dataset for run your code

### ISSUE THREAD

**Issue by perfect0222** [GuptaSheshu/fourier-ptychography#1]
first, to run generate_fpm.m, I need the original dataset as images below the path , "/home/legion/nownow/fourier_ptychography/data/jpg1/" and "/home/legion/nownow/fourier_ptychography/data/jpg1/".
second, to run began.py, I need the original dataset as images organized as the file in "../data/25_stacks/x_train.npy"
thanks,

**Comment by GuptaSheshu** [comment]
We have used INRIA dataset, you can choose practically any set of random images here. As far as INRIA dataset is concern, here is the [link](https://lear.inrialpes.fr/~jegou/data.php), there are two zip files and that is exactly what is been referred to as "jpg1" and "jpg2" in folder above. I hope this helps.
